package edtech.afrilingo.certification;

public enum ProctorEventType {
    FACE_NOT_DETECTED,
    MULTIPLE_FACES_DETECTED,
    EXTENDED_LOOK_AWAY,
    PROHIBITED_OBJECT_DETECTED,
    SUSPICIOUS_MOVEMENT,
    AUDIO_ANOMALY,
    BROWSER_TAB_CHANGE,
    COPY_PASTE_ATTEMPT,
    SCREENSHOT_ATTEMPT,
    SESSION_START,
    SESSION_END,
    WARNING_ISSUED,
    SESSION_TERMINATED,
    INACTIVITY_DETECTED,
    APP_FOCUS_LOST
}
